project:
  type: website
  output-dir: docs
website:
  title: "Water Control Valves Blog."
  site-url: https://ratral.github.io/Control_Valves_Blog/
  description: "This blog is a compilation of my notes on the selection of control valves."
  navbar:
    background: "green"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ratral
      - icon: twitter
        href: https://twitter.com/Dr_Raul
format:
  html:
    theme: 
      ligth: litera
      dark: darkly
    highlight-style: eiffel
    css: styles.css
