project:
  type: website
  output-dir: docs

website:
  title: "Water Control Valves Blog."
  description: "This is Dr. Raúl Trujillo personal Blog."
  navbar:
    background: "green"
    left: 
      - "Dr. Raúl Trujillo Álvarez"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ratral
      - icon: twitter
        href: https://twitter.com/Dr_Raul
format:
  html:
    theme: 
      ligth: litera
      dark: darkly
    highlight-style: eiffel
    css: styles.css
