project:
  type: website
  output-dir: docs

website:
  title: "Control Valves Blog."
  description: "This is Dr. Raúl Trujillo personal Blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ratral
      - icon: twitter
        href: https://twitter.com/Dr_Raul
format:
  html:
    theme: cosmo
    css: styles.css



