---
title: "Remarks about  plunger valves"
date: "2022-08-24"
categories: [backgrounds, knowledge, valves, valves]
description: ''
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# Remarks about  plunger valves

 Plunger valves are mainly used where volume flows, or pressure has to be reduced and regulated without vibrations, noises, or significant changes in the pipeline system.  valves are control devices that cause pressure loss in pipeline systems by throttling to modify the flow or pressure so that the desired values are obtained, depending on the degree of opening adjustment.

The following advantages are obtained from the plunger valves :

  - universal use wide controllable range;
  - low cavitation coefficient, stable flow, low noise;
  - flow block is variable: optimum flow for every operating condition;
  - low drive forces with pressure-relieving fix and mobile cylinder (pistons).
  
To size a control valve, the following points must be considered :

  - The control valve must permit the maximum flow (1.3 times the maximum flow required for the application ) under the lowest-possible differential pressure.
  - The flow range (maximum, median, and minimum) relative to the degree of opening of the control valve must be such that the regulation circuit is stable.
  - In the entire control range (maximum, median, and minimum), there should be no occurrence of cavitation.
  - The pipeline systems are planned and installed, bearing in mind future requirements. It is often forgotten that control valves designed for these end capacities are over-sized at the start of the operation but not for future needs. Reducing the size of the control valve means generating additional problems and costs in the future of system operation.
  
One of the most uncomfortable things that can a hydraulic design to happen is a valve chosen six months or a year ago deteriorating. The most common causes of premature valve failure are:

  - Cavitation damage.
  - Cavitation and flashing of water (shock flow).
  - Erosion of the valve.
  - Vibration (irregular flow pattern with liquids).
  - Corrosion.
  - Leakages.
  
To avoid in any way, the following design criteria must be met [@baumann2009]:

  1. Criteria for valve selection :
    - Is the valve appropriately sized?
    - Does the valve have a low dead band, sometimes confused with hysteresis?
    - Will it be able to operate without a positioner (also a cost factor)?
    - Does it have adequate rangeability?
    - Is the flow characteristic acceptable (installed characteristic)?
    - How is its dynamic performance (frequency response, time constant)?

  2. Installation and effects on the environment:
    - Is face-to-face such that it can be replaced with another make?
    - How heavy is it?
    - Are supports needed?
    - Is it too tall?
    - Is it going to be noisy under the given flow conditions?
    - Is there an energy supply (in the case of electric actuators)?
    - Can it withstand the corrosive effects of fluid and the environment?
    - Would the valve be cavitating under the given flow conditions?
    - If outdoors, can the valve and actuator stand extreme weather conditions?

  3. Maintainability and long-term cost:
    - Is it easy to repair?
    - What are the prices of spare parts?
    - Can the actuator tolerate a vibrating environment?
    - How is the actuator protected from corrosion?
    - Is the packing field replaceable?
    - Is the control cylinders (fixed and mobile) field-replaceable?
    - Is the actuator able to diagnose the valve?
    
Another essential point to consider is the information available. Sizing the flow to the fifth place after the decimal point is all well and good, but only if you know the proper process conditions :

  - First, the valve should be sized to control the maximum flow rate under the lowest-possible differential pressure. But what is maximum flow exactly?
  - How about emergency conditions?
  - On the other hand, should the valve fail open, would the resultant flow be more than the downstream pipe or valve could handle?
  - What are the correct inlet pressures?
  - What are the variations in inlet pressures?
  - Can you use the head pressure of the pump from the manufacturers published curve? (If you do, use the head pressure corresponding to the maximum flow the valve has to pass, and don't ignore the static head at the pumps location.)
  - How about line losses?
  
My experience is that all these questions will be answered in a vague form from the design people. They don’t know either and have to rely on the input from other departments. The result is usually guesswork with ample safety factors thrown in.

**Only after reviewing these criteria and deciding on the proper valve type should the subject of cost be considered.**

## References:

Baumann, Hans D. Control Valve Primer: A User’s Guide. 4th ed, ISA, 2009.

